/**
 * THE MEMORY CONTRACT
 *
 * Any database system (Supabase, Firebase, Mongo, SQL) that wants to work
 * with the Tripzy Autonomous Engine must implement this interface.
 */

export interface IMemoryAdapter {
  /**
   * Persist a user signal (click, view, etc.) to the database.
   */
  saveSignal(signal: any): Promise<void>;

  /**
   * Batch persist user signals.
   */
  saveSignals(signals: any[]): Promise<void>;

  /**
   * Perform a semantic/vector search for relevant content.
   * @param vector - The embedding vector generated by the Brain (Layer 2)
   * @param limit - Max results
   */
  searchVectors(vector: number[], limit?: number): Promise<any[]>;

  /**
   * Retrieve valid content items (e.g. products, posts) based on IDs.
   * Used to hydrate recommendations with real data.
   */
  getContentByIds(ids: string[]): Promise<any[]>;
}

/**
 * Base abstract class to allow partial implementations or shared logic later.
 */
export abstract class BaseMemoryAdapter implements IMemoryAdapter {
  abstract saveSignal(signal: any): Promise<void>;
  abstract saveSignals(signals: any[]): Promise<void>;
  abstract searchVectors(vector: number[], limit?: number): Promise<any[]>;
  abstract getContentByIds(ids: string[]): Promise<any[]>;
}
