// Localization system for Tripzy Lifestyle Adventures Blog
// English and Turkish translations

export type Language = 'en' | 'tr';

export interface Translations {
  // Header & Navigation
  header: {
    home: string;
    tripPlanner: string;
    about: string;
    contact: string;
    login: string;
    tripzyDeals: string;
  };
  // Footer
  footer: {
    tagline: string;
    about: string;
    aboutText: string;
    quickLinks: string;
    followUs: string;
    newsletter: string;
    newsletterText: string;
    emailPlaceholder: string;
    subscribe: string;
    copyright: string;
  };
  // Trip Planner Page
  tripPlanner: {
    badge: string;
    title: string;
    subtitle: string;
    destinationPlaceholder: string;
    duration: string;
    days: string;
    generateButton: string;
    planning: string;
    localInsightsTitle: string;
    localInsightsDesc: string;
    mapGroundingTitle: string;
    mapGroundingDesc: string;
    personalizedTitle: string;
    personalizedDesc: string;
    buildingTrip: string;
    buildingTripDesc: string;
    yourTrip: string;
    generatedBy: string;
    verifiedLocations: string;
    viewOnMaps: string;
    travelTip: string;
    travelTipText: string;
  };
  // Blog
  blog: {
    readMore: string;
    relatedPosts: string;
    leaveComment: string;
    yourName: string;
    yourEmail: string;
    yourComment: string;
    submitComment: string;
    comments: string;
    noComments: string;
    shareArticle: string;
    categories: string;
    tags: string;
    by: string;
    on: string;
    min: string;
    readTime: string;
    views: string;
  };
  // Common
  common: {
    loading: string;
    error: string;
    success: string;
    cancel: string;
    save: string;
    delete: string;
    edit: string;
    search: string;
    searchPlaceholder: string;
  };
  // Login Page
  login: {
    title: string;
    subtitle: string;
    googleButton: string;
    or: string;
    emailLabel: string;
    passwordLabel: string;
    submitButton: string;
    backToWebsite: string;
    errorEmpty: string;
    errorFailedGoogle: string;
  };
}

export const translations: Record<Language, Translations> = {
  en: {
    header: {
      home: 'Home',
      tripPlanner: 'Trip Planner',
      about: 'About',
      contact: 'Contact',
      login: 'Login',
      tripzyDeals: 'Tripzy Deals',
    },
    footer: {
      tagline: 'Where every journey becomes a lifestyle',
      about: 'About',
      aboutText: 'Tripzy Lifestyle Adventures is your gateway to discovering the world. From hidden gems to popular destinations, we help you plan unforgettable journeys with AI-powered insights.',
      quickLinks: 'Quick Links',
      followUs: 'Follow Us',
      newsletter: 'Newsletter',
      newsletterText: 'Get travel tips and exclusive deals delivered to your inbox',
      emailPlaceholder: 'Enter your email',
      subscribe: 'Subscribe',
      copyright: '© 2025 Tripzy Lifestyle Adventures. All rights reserved.',
    },
    tripPlanner: {
      badge: 'AI Powered Planning',
      title: 'Where will your next',
      subtitle: 'Our AI travel consultant uses real-time Google data to build the perfect day-by-day itinerary just for you.',
      destinationPlaceholder: 'e.g., Tokyo, Japan',
      duration: 'Duration',
      days: 'Days',
      generateButton: 'Generate Itinerary',
      planning: 'Planning...',
      localInsightsTitle: 'Local Insights',
      localInsightsDesc: 'Hidden gems suggested by real-time web searches.',
      mapGroundingTitle: 'Map Grounding',
      mapGroundingDesc: 'Direct links to verified Google Maps locations.',
      personalizedTitle: 'Personalized',
      personalizedDesc: 'Tailored day-by-day flows for your time frame.',
      buildingTrip: 'Building your dream trip...',
      buildingTripDesc: 'Gemini is currently cross-referencing maps, reviews, and latest travel guides to find the best spots in',
      yourTrip: 'Your',
      generatedBy: 'Generated by Gemini Intelligence',
      verifiedLocations: 'Verified Locations',
      viewOnMaps: 'View on Google Maps',
      travelTip: 'Travel Tip',
      travelTipText: 'Always check local opening hours as they may vary seasonally. This itinerary is live-generated based on current top-rated data.',
    },
    blog: {
      readMore: 'Read More',
      relatedPosts: 'Related Posts',
      leaveComment: 'Leave a Comment',
      yourName: 'Your Name',
      yourEmail: 'Your Email',
      yourComment: 'Your Comment',
      submitComment: 'Submit Comment',
      comments: 'Comments',
      noComments: 'No comments yet. Be the first to comment!',
      shareArticle: 'Share this article',
      categories: 'Categories',
      tags: 'Tags',
      by: 'by',
      on: 'on',
      min: 'min',
      readTime: 'read',
      views: 'views',
    },
    common: {
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      cancel: 'Cancel',
      save: 'Save',
      delete: 'Delete',
      edit: 'Edit',
      search: 'Search',
      searchPlaceholder: 'Search posts...',
    },
    login: {
      title: 'Tripzy Lifestyle',
      subtitle: 'Welcome back, Traveler',
      googleButton: 'Continue with Google',
      or: 'OR',
      emailLabel: 'Email Address',
      passwordLabel: 'Password',
      submitButton: 'Sign In to Dashboard',
      backToWebsite: 'Back to website',
      errorEmpty: 'Please enter both email and password.',
      errorFailedGoogle: 'Failed to sign in with Google.',
    },
  },
  tr: {
    header: {
      home: 'Ana Sayfa',
      tripPlanner: 'Gezi Planlayıcı',
      about: 'Hakkında',
      contact: 'İletişim',
      login: 'Giriş',
      tripzyDeals: 'Tripzy Fırsatlar',
    },
    footer: {
      tagline: 'Her yolculuk bir yaşam tarzı',
      about: 'Hakkında',
      aboutText: 'Tripzy Lifestyle Adventures, dünyayı keşfetmeniz için kapınızdır. Gizli cennetlerden popüler destinasyonlara kadar yapay zeka destekli önerilerle unutulmaz yolculuklar planlamanıza yardımcı oluyoruz.',
      quickLinks: 'Hızlı Bağlantılar',
      followUs: 'Takip Edin',
      newsletter: 'Bülten',
      newsletterText: 'Seyahat ipuçları ve özel fırsatları e-postanıza alın',
      emailPlaceholder: 'E-postanızı girin',
      subscribe: 'Abone Ol',
      copyright: '© 2025 Tripzy Lifestyle Adventures. Tüm hakları saklıdır.',
    },
    tripPlanner: {
      badge: 'Yapay Zeka Destekli Planlama',
      title: 'Bir sonraki',
      subtitle: 'Yapay zeka seyahat danışmanımız, sizin için mükemmel günlük program oluşturmak üzere Google\'ın gerçek zamanlı verilerini kullanır.',
      destinationPlaceholder: 'örn., Tokyo, Japonya',
      duration: 'Süre',
      days: 'Gün',
      generateButton: 'Program Oluştur',
      planning: 'Planlanıyor...',
      localInsightsTitle: 'Yerel İpuçları',
      localInsightsDesc: 'Gerçek zamanlı web aramalarıyla önerilen gizli cennetler.',
      mapGroundingTitle: 'Harita Doğrulama',
      mapGroundingDesc: 'Doğrulanmış Google Maps konumlarına doğrudan bağlantılar.',
      personalizedTitle: 'Kişiselleştirilmiş',
      personalizedDesc: 'Zaman diliminize göre özelleştirilmiş günlük akışlar.',
      buildingTrip: 'Hayalinizdeki gezi oluşturuluyor...',
      buildingTripDesc: 'Gemini şu anda haritaları, yorumları ve en güncel seyahat rehberlerini karşılaştırarak',
      yourTrip: 'Sizin',
      generatedBy: 'Gemini Intelligence tarafından oluşturuldu',
      verifiedLocations: 'Doğrulanmış Konumlar',
      viewOnMaps: 'Google Maps\'te Görüntüle',
      travelTip: 'Seyahat İpucu',
      travelTipText: 'Açılış saatleri mevsimsel olarak değişebileceğinden her zaman yerel saatleri kontrol edin. Bu program, güncel en yüksek puanlı verilere göre canlı olarak oluşturulmuştur.',
    },
    blog: {
      readMore: 'Devamını Oku',
      relatedPosts: 'İlgili Yazılar',
      leaveComment: 'Yorum Yap',
      yourName: 'Adınız',
      yourEmail: 'E-postanız',
      yourComment: 'Yorumunuz',
      submitComment: 'Yorum Gönder',
      comments: 'Yorumlar',
      noComments: 'Henüz yorum yok. İlk yorumu siz yapın!',
      shareArticle: 'Bu yazıyı paylaş',
      categories: 'Kategoriler',
      tags: 'Etiketler',
      by: 'yazar',
      on: 'tarih',
      min: 'dk',
      readTime: 'okuma',
      views: 'görüntülenme',
    },
    common: {
      loading: 'Yükleniyor...',
      error: 'Hata',
      success: 'Başarılı',
      cancel: 'İptal',
      save: 'Kaydet',
      delete: 'Sil',
      edit: 'Düzenle',
      search: 'Ara',
      searchPlaceholder: 'Yazı ara...',
    },
    login: {
      title: 'Tripzy Lifestyle',
      subtitle: 'Hoş geldiniz, Gezgin',
      googleButton: 'Google ile Devam Et',
      or: 'VEYA',
      emailLabel: 'E-posta Adresi',
      passwordLabel: 'Şifre',
      submitButton: 'Panele Giriş Yap',
      backToWebsite: 'Web sitesine dön',
      errorEmpty: 'Lütfen hem e-posta hem de şifre girin.',
      errorFailedGoogle: 'Google ile giriş yapılamadı.',
    },
  },
};
