import React, { useState } from "react";
import { X, Sparkles, FileText, ClipboardList } from "lucide-react";
import { postService } from "../../services/postService";
import { aiContentService } from "../../services/aiContentService";
import { useAuth } from "../../hooks/useAuth";
import { PostStatus, Post } from "../../types";

interface ImportViralPostModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
}

const ImportViralPostModal: React.FC<ImportViralPostModalProps> = ({
  isOpen,
  onClose,
  onSuccess,
}) => {
  const { user } = useAuth();
  const [activeTab, setActiveTab] = useState<"paste" | "perplexity">("paste");
  const [loading, setLoading] = useState(false);

  // Form State
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [excerpt, setExcerpt] = useState("");

  if (!isOpen) return null;

  const handleSmartImport = async () => {
    if (!title || !content) {
      alert("Please enter a title and content.");
      return;
    }

    setLoading(true);
    try {
      // Basic cleanup of pasted content
      let processedContent = content;

      // Wrap in article tag if missing
      if (!processedContent.includes("<article>")) {
        processedContent = `<article>${processedContent}</article>`;
      }

      // Strip inline color and background styles to ensure theme compatibility
      processedContent = processedContent
        .replace(/color:\s*#[0-9a-f]{3,6};?/gi, "")
        .replace(/background-color:\s*#[0-9a-f]{3,6};?/gi, "")
        .replace(/background:\s*#[0-9a-f]{3,6};?/gi, "");

      // AI Enhancement: Generate Tags & SEO if possible
      let generatedTags = ["Viral", "Trending"];
      let generatedMetaDesc = "";

      try {
        const seoResult = await aiContentService.generateSEO(
          title,
          processedContent
        );
        if (seoResult.metaKeywords) {
          generatedTags = [
            ...new Set([
              ...generatedTags,
              ...seoResult.metaKeywords.split(",").map((s) => s.trim()),
            ]),
          ];
        }
        generatedMetaDesc = seoResult.metaDescription || "";
      } catch (err) {
        console.warn("Auto-tagging failed:", err);
      }

      const newPost: Partial<Post> = {
        title,
        content: processedContent,
        excerpt:
          excerpt || generatedMetaDesc || content.substring(0, 150) + "...",
        authorId: user?.id,
        status: PostStatus.Draft,
        category: "Trending",
        tags: generatedTags,
        views: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        slug: "", // Will be generated by backend/service
      };

      // @ts-ignore - The service expects a full Post object but we're sending what we have
      await postService.createPost(newPost as any);

      onSuccess();
      onClose();
    } catch (error) {
      console.error("Import failed:", error);
      alert("Failed to import post. See console for details.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-navy-950/80 backdrop-blur-md animate-in fade-in duration-300">
      <div className="bg-navy-900 border border-gold/20 rounded-3xl w-full max-w-2xl shadow-2xl overflow-hidden animate-in zoom-in-95 duration-300 flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="p-6 border-b border-white/5 flex items-center justify-between bg-navy-950/50">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-purple-500/10 flex items-center justify-center text-purple-400">
              <Sparkles size={20} />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white font-serif">
                Import Viral Content
              </h2>
              <p className="text-xs text-gray-400">
                Paste directly from Perplexity, ChatGPT, or your research.
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-white/5 rounded-full text-gray-400 hover:text-white transition-colors"
          >
            <X size={20} />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6 custom-scrollbar">
          {/* Title Input */}
          <div className="space-y-2">
            <label className="text-xs font-bold text-gray-400 uppercase tracking-widest ml-1">
              Title
            </label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g., The Hidden Gem of the Japanese Alps..."
              className="w-full bg-navy-800/50 border border-white/10 rounded-xl px-4 py-3 text-white focus:border-gold/50 focus:outline-none transition-colors"
            />
          </div>

          {/* Excerpt Input */}
          <div className="space-y-2">
            <label className="text-xs font-bold text-gray-400 uppercase tracking-widest ml-1">
              Short Summary / Excerpt
            </label>
            <textarea
              value={excerpt}
              onChange={(e) => setExcerpt(e.target.value)}
              placeholder="Enter a catchy summary (optional)..."
              rows={2}
              className="w-full bg-navy-800/50 border border-white/10 rounded-xl px-4 py-3 text-white focus:border-gold/50 focus:outline-none transition-colors"
            />
          </div>

          {/* Main Content Input */}
          <div className="space-y-2 flex-1 flex flex-col">
            <label className="text-xs font-bold text-gray-400 uppercase tracking-widest ml-1 flex justify-between">
              <span>Main Content (HTML or Markdown)</span>
              <span className="text-purple-400 text-[10px] normal-case bg-purple-500/10 px-2 py-0.5 rounded-full border border-purple-500/20">
                Supports Paste from Perplexity
              </span>
            </label>
            <textarea
              value={content}
              onChange={(e) => setContent(e.target.value)}
              placeholder="<p>Paste the full article content here...</p>"
              className="w-full flex-1 min-h-[300px] bg-navy-800/50 border border-white/10 rounded-xl px-4 py-3 text-gray-300 font-mono text-sm focus:border-gold/50 focus:outline-none transition-colors resize-none"
            />
          </div>
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-white/5 bg-navy-950/50 flex justify-end gap-3">
          <button
            onClick={onClose}
            className="px-6 py-2.5 rounded-xl text-gray-400 hover:text-white font-bold transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={handleSmartImport}
            disabled={loading || !title || !content}
            className="px-8 py-2.5 bg-gradient-to-r from-purple-500 to-indigo-600 hover:from-purple-400 hover:to-indigo-500 text-white rounded-xl font-bold shadow-lg shadow-purple-500/20 disabled:opacity-50 disabled:cursor-not-allowed transition-all flex items-center gap-2"
          >
            {loading ? (
              <>
                <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                Processing...
              </>
            ) : (
              <>
                <FileText size={18} />
                Create Draft Post
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};

export default ImportViralPostModal;
