-- Migration 016: Phase 2 Agent Infrastructure
-- Establish the user_archetypes table for psychographic profiling.

-- Set search path to blog schema (as per institutional standard)
SET search_path TO blog, public;

CREATE TABLE IF NOT EXISTS blog.user_archetypes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    archetype TEXT NOT NULL,
    confidence_score FLOAT NOT NULL,
    primary_motivations JSONB DEFAULT '[]'::jsonb,
    vibe_shift_directive TEXT,
    xai_explanation TEXT,
    full_psychographics JSONB DEFAULT '{}'::jsonb,
    last_updated TIMESTAMPTZ DEFAULT now(),
    UNIQUE(user_id)
);

-- Indexing for fast retrieval
CREATE INDEX idx_user_archetypes_user_id ON blog.user_archetypes(user_id);

-- Commentary
COMMENT ON TABLE blog.user_archetypes IS 'Stores high-fidelity psychographic profiles generated by the ProfilerAgent for Personalized R&D.';
